version : "3.8"

services:

  frontend: 
    build:
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  oauth:
    build:
      context: /oauth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  shopping:
    build:
      context: /shopping
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

